name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Переходим в директорию, где будет размещен сайт
          cd /var/www/usual/Usual.dev
      
          # Удаляем предыдущее содержимое директории
          rm -rf *

          # Клонируем репозиторий
          git clone git@github.com:thatspock/Usual.dev.git temp_dir

          # Перемещаем содержимое папки dist из клонированного репозитория
          mv temp_dir/dist/* .

          # Удаляем временную директорию с клонированным репозиторием
          rm -rf temp_dir

          echo 'Deployment successful to digital ocean'
