name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # Можно изменить на версию Node.js, которая требуется для вашего проекта

    - name: Install dependencies
      run: npm install
      
    - name: Fix errors and build project
      run: npm run fixAndBuild # Использует ваш новый скрипт для исправления и сборки

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USERNAME}}
        key: ${{secrets.SSH_KEY}}
        script: |
          cd /var/www/usual/Usual.dev
          # Сюда можно добавить команды для удаления старых файлов, если это необходимо
          # Например, можно использовать rsync для синхронизации файлов сборки
          rsync -avz --delete ./dist/ root@159.89.99.171:/var/www/usual/Usual.dev/
          # Обязательно замените ./dist/ на путь к вашей папке с результатами сборки, если он отличается
