name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/usual
          rm -rf Usual.dev
          git clone git@github.com:thatspock/Usual.dev.git Usual.dev
          echo 'Deployment successful to digital ocean'
